# Generated by Django 5.2.14 on 2026-07-03 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TrelloBoardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_id', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(default='api', max_length=24)),
                ('raw_payload', models.JSONField(default=dict)),
                ('cards_count', models.PositiveIntegerField(default=0)),
                ('movements_count', models.PositiveIntegerField(default=0)),
                ('custom_field_changes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='trello_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.trelloboardsnapshot'),
        ),
        migrations.CreateModel(
            name='TrelloCardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(max_length=300)),
                ('current_list_id', models.CharField(blank=True, max_length=80)),
                ('current_list_name', models.CharField(blank=True, max_length=180)),
                ('closed', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at_trello', models.DateTimeField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('date_last_activity', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('id_short', models.IntegerField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('description_data', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='reports.trelloboardsnapshot')),
            ],
            options={
                'ordering': ('current_list_name', 'name'),
                'indexes': [models.Index(fields=['snapshot', 'trello_id'], name='reports_tre_snapsho_e130ab_idx'), models.Index(fields=['snapshot', 'current_list_name'], name='reports_tre_snapsho_0fb008_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrelloCustomFieldChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(db_index=True, max_length=80)),
                ('card_name', models.CharField(blank=True, max_length=300)),
                ('field_name', models.CharField(max_length=180)),
                ('at', models.DateTimeField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('actor_id', models.CharField(blank=True, max_length=80)),
                ('actor_name', models.CharField(blank=True, max_length=180)),
                ('action_id', models.CharField(blank=True, max_length=80)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_changes', to='reports.trelloboardsnapshot')),
            ],
            options={
                'ordering': ('at',),
                'indexes': [models.Index(fields=['snapshot', 'card_id'], name='reports_tre_snapsho_1d393b_idx'), models.Index(fields=['snapshot', 'field_name'], name='reports_tre_snapsho_e97501_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrelloListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('closed', models.BooleanField(default=False)),
                ('pos', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='reports.trelloboardsnapshot')),
            ],
            options={
                'ordering': ('pos', 'name'),
                'indexes': [models.Index(fields=['snapshot', 'trello_id'], name='reports_tre_snapsho_8cc142_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrelloMovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(db_index=True, max_length=80)),
                ('card_name', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField()),
                ('event_type', models.CharField(max_length=40)),
                ('from_list_id', models.CharField(blank=True, max_length=80)),
                ('from_list_name', models.CharField(blank=True, max_length=180)),
                ('to_list_id', models.CharField(blank=True, max_length=80)),
                ('to_list_name', models.CharField(blank=True, max_length=180)),
                ('actor_id', models.CharField(blank=True, max_length=80)),
                ('actor_name', models.CharField(blank=True, max_length=180)),
                ('action_id', models.CharField(blank=True, max_length=80)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='reports.trelloboardsnapshot')),
            ],
            options={
                'ordering': ('at',),
                'indexes': [models.Index(fields=['snapshot', 'card_id'], name='reports_tre_snapsho_e8b97d_idx'), models.Index(fields=['snapshot', 'event_type'], name='reports_tre_snapsho_f69e3c_idx')],
            },
        ),
    ]
